version: '3.8'

services:
  # PostgreSQL (if not using existing FrameKraft DB)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: framekraft
      POSTGRES_USER: frameforge
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U frameforge"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # API Server
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://frameforge:your_secure_password@postgres:5432/framekraft
      - REDIS_URL=redis://redis:6379
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/app/models
      - CDN_BASE_URL=http://localhost:3000/models
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run dev

  # Worker
  worker:
    build: .
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://frameforge:your_secure_password@postgres:5432/framekraft
      - REDIS_URL=redis://redis:6379
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/app/models
      - CDN_BASE_URL=http://localhost:3000/models
      - WORKER_CONCURRENCY=2
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run worker

volumes:
  postgres_data:
  redis_data:
